In [1]:
# comp_name = CSV.read("data/constituents_csv.csv")
# for i in 1:((size(comp_name))[1]-1)
#     #println("https://query1.finance.yahoo.com/v7/finance/download/",comp_name[i,1],"?period1=946706400&period2=1514786400&interval=1mo&events=history&crumb=UB6zx5WdF5I")
# end

In [1]:
# HELPER FUNCTION TO CALCULATE RATIO OF RETURN
# ratio of return in a monthly base
function get_monthly_return(csv_data)
    montly_return = Float64[]
    for i in 1:((size(csv_data))[1]-1)
        append!(montly_return, (csv_data[i+1,5]-csv_data[i,5])/csv_data[i,5])
    end  
    return montly_return
end;    

In [173]:
using CSV, LinearAlgebra
# remove those files(not long enough)
data_files = readdir("top30")
total_monthly_return = zeros(215)
valid_data = zeros(216)

for i in data_files
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    csv_length = (size(csv_data))[1]
    # check all csv has the same length (no new/removed S&P 500)
    if csv_length != 216
        print(file_path, ": ")
        println(csv_length)
    else
        valid_data = hcat(valid_data, csv_data[:,5])        
        total_monthly_return = hcat(total_monthly_return, get_monthly_return(csv_data))
    end
end    

valid_data = valid_data[:, 2:end]
total_monthly_return = total_monthly_return[:, 2:end]

top30/ABBV.csv: 60
top30/ADS.csv: 199
top30/AIZ.csv: 167
top30/ALGN.csv: 204
top30/AVGO.csv: 101
top30/AYI.csv: 193
top30/CBOE.csv: 91
top30/CME.csv: 181
top30/DG.csv: 98
top30/DISCA.csv: 150
top30/EQIX.csv: 209
top30/FTV.csv: 18
top30/GOOGL.csv: 161
top30/HCA.csv: 82
top30/HII.csv: 82
top30/HLT.csv: 49
top30/KHC.csv: 30
top30/KMI.csv: 83
top30/LYB.csv: 93
top30/MDLZ.csv: 199
top30/NAVI.csv: 45
top30/NLSN.csv: 84
top30/NRG.csv: 169
top30/NWSA.csv: 55
top30/PM.csv: 118
top30/PPG.csv: 2
top30/RTN.csv: 276
top30/STX.csv: 181
top30/SYF.csv: 42
top30/TDG.csv: 142
top30/TEL.csv: 127
top30/UA.csv: 30
top30/V.csv: 118
top30/WRK.csv: 31
top30/WYNN.csv: 183


215×129 Array{Float64,2}:
  0.104819    -0.196552    -0.143617    …   0.743169   -0.0698691 
  0.184842     0.0300429    0.0248447       0.0384013   0.166667  
 -0.0865162    0.333333    -0.0363637      -0.115472    0.0905433 
 -0.322922     0.2125       0.201258        0.0392491  -0.134686  
  0.247024     0.278994    -0.17801         0.0845649  -0.0362474 
 -0.0298329    0.126449    -0.0445859   …  -0.0908403  -0.141593  
  0.199262     0.00536673  -0.0112529       0.184013    0.201674  
 -0.577436     0.338078    -0.023006       -0.0365682   0.0509393 
 -0.240292    -0.0757979    0.275362       -0.154015   -0.0204081 
 -0.15655      0.133813     0.159091       -0.461605    0.2       
 -0.0984845    0.0253807    0.17647     …   0.182692   -0.0833333 
  0.453782    -0.0528713   -0.00466662      0.170732    0.0915152 
 -0.15607      0.123144     0.00803746     -0.280093    0.0688506 
  ⋮                                     ⋱                         
  0.0477465    0.116255    -0.030449

In [3]:
num_time_period = size(total_monthly_return)[1]
num_stock = size(total_monthly_return)[2]

# mean of monthly return of a stock
using Statistics
expected_monthly_return = Float64[]
for i in 1:size(total_monthly_return)[2]
    push!(expected_monthly_return, mean(total_monthly_return[:,i]))
end
expected_monthly_return

129-element Array{Float64,1}:
 0.025585884938832314 
 0.016912595764853138 
 0.009564503171370812 
 0.007014600703790782 
 0.005397906212492487 
 0.016519475094170087 
 0.015524168594298294 
 0.016263200737921635 
 0.016155426487548447 
 0.023064400886971745 
 0.01092046897112602  
 0.01049504978008741  
 0.019188604844708784 
 ⋮                    
 0.010202314552856976 
 0.009012570445919637 
 0.01900224488440054  
 0.009288300060753934 
 0.013756442432663793 
 0.016681222100094976 
 0.0019328706496993188
 0.012594881969745533 
 0.009612927352649934 
 0.004164458380570289 
 0.008563595437728933 
 0.015380230394524868 

In [4]:
# Σ
# convolution between stocks
cov_matrix = transpose(total_monthly_return)*total_monthly_return./num_time_period
        -expected_monthly_return*transpose(expected_monthly_return)

129×129 Array{Float64,2}:
 -0.000654638  -0.000432724  -0.000244716  …  -0.000219107  -0.000393517
 -0.000432724  -0.000286036  -0.000161761     -0.000144833  -0.00026012 
 -0.000244716  -0.000161761  -9.14797e-5      -8.19065e-5   -0.000147104
 -0.000179475  -0.000118635  -6.70912e-5      -6.00702e-5   -0.000107886
 -0.00013811   -9.12926e-5   -5.16283e-5      -4.62255e-5   -8.3021e-5  
 -0.000422665  -0.000279387  -0.000158001  …  -0.000141466  -0.000254073
 -0.0003972    -0.000262554  -0.000148481     -0.000132943  -0.000238765
 -0.000416108  -0.000275053  -0.000155549     -0.000139271  -0.000250132
 -0.000413351  -0.00027323   -0.000154519     -0.000138349  -0.000248474
 -0.000590123  -0.000390079  -0.0002206       -0.000197514  -0.000354736
 -0.00027941   -0.000184693  -0.000104449  …  -9.35185e-5   -0.000167959
 -0.000268525  -0.000177499  -0.00010038      -8.98754e-5   -0.000161416
 -0.000490957  -0.000324529  -0.000183529     -0.000164323  -0.000295125
  ⋮                      

In [5]:
baseline_profit = 0.01
mT = transpose(expected_monthly_return)

using JuMP, Gurobi
m = Model(solver=GurobiSolver(OutputFlag=0))
@variable(m, w[1:num_stock])
@objective(m, Min, dot(w,cov_matrix*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Academic license - for non-commercial use only
Optimal


129-element Array{Float64,1}:
  0.007108407340855522 
  0.03647864473049046  
 -0.005775556476774045 
 -0.003189883506351814 
 -0.08110973755242526  
  0.0026888480093362134
 -0.029219116856031794 
 -0.08684272198938832  
  0.06800140178301012  
  0.008537710143941609 
 -0.00357649687628895  
 -0.030277104265095438 
 -0.02198331965221331  
  ⋮                    
 -0.09021261827929782  
  0.027742781657780567 
  0.047493594696279604 
  0.026949404536924095 
  0.010139574569564259 
  0.047024739990467204 
  0.0068385379752427195
 -0.020378217995989146 
  0.00919529283248459  
  0.14607991854623822  
 -0.03150761380468012  
  0.014453430511462624 

In [6]:
# mean of monthly return of a stock
using Statistics

function get_expected_monthly_return(total_monthly_return)
    expected_monthly_return = Float64[]
    for i in 1:size(total_monthly_return)[2]
        push!(expected_monthly_return, mean(total_monthly_return[:,i]))
    end
    return expected_monthly_return
end

function get_cov_matrix(total_monthly_return, expected_monthly_return)
    return transpose(total_monthly_return)*total_monthly_return./size(total_monthly_return)[2]-expected_monthly_return*transpose(expected_monthly_return)
end

get_cov_matrix (generic function with 1 method)

In [51]:
# US treasurt securities data in %
risk_free = CSV.read("data/risk_free.csv")
risk_free_15 = mean(risk_free[2:180,2])/100

0.03803351955307261

In [52]:
risk_free_10 = mean(risk_free[62:180,2])/100

0.03317899159663869

In [54]:
# US treasurt securities data in %
index_data = CSV.read("data/index.csv")
index_monthly_return_15 = get_monthly_return(index_data[1:180,:])
index_monthly_return_10 = get_monthly_return(index_data[61:180,:])

119-element Array{Float64,1}:
  0.018903346078316657  
 -0.019117655748441098  
 -0.020108581881679344  
  0.02995204626256571   
 -0.0001427142257658092 
  0.0359682871938124    
 -0.01122210487449661   
  0.006949024694760399  
 -0.017740780066319385  
  0.03518609592972647   
 -0.0009523489924185018 
  0.025466771348641722  
  0.00045315763072534016
  ⋮                     
 -0.035582905675162646  
  0.043117029976595334  
  0.006932165607935714  
  0.006200788965052755  
  0.02103028001299596   
  0.019058331658920603  
 -0.015079830581919834  
  0.037655295489735195  
 -0.015513837223063749  
  0.023201460786772227  
  0.024533588760364766  
 -0.004188587877920406  

In [10]:
# HELPER FUNCTION TO CALCULATE RATIO OF RETURN
# ratio of return in a monthly base
function get_monthly_return_stock(csv_data)
    montly_return = Float64[]
    for i in 1:((size(csv_data))[1]-1)
        append!(montly_return, (csv_data[i+1,1]-csv_data[i,1])/csv_data[i,1])
    end  
    return montly_return
end;    

In [11]:
using CSV, LinearAlgebra
# remove those files(not long enough)
length_15 = 180-1
total_monthly_return_15 = zeros(length_15)

for i in 1:num_stock
    total_monthly_return_15 = hcat(total_monthly_return_15, get_monthly_return_stock(valid_data[1:180,i]))
end    

total_monthly_return_15 = total_monthly_return_15[:, 2:end]

179×129 Array{Float64,2}:
  0.104819   -0.196552    -0.143617    …   0.743169    -0.0698691 
  0.184842    0.0300429    0.0248447       0.0384013    0.166667  
 -0.0865162   0.333333    -0.0363637      -0.115472     0.0905433 
 -0.322922    0.2125       0.201258        0.0392491   -0.134686  
  0.247024    0.278994    -0.17801         0.0845649   -0.0362474 
 -0.0298329   0.126449    -0.0445859   …  -0.0908403   -0.141593  
  0.199262    0.00536673  -0.0112529       0.184013     0.201674  
 -0.577436    0.338078    -0.023006       -0.0365682    0.0509393 
 -0.240292   -0.0757979    0.275362       -0.154015    -0.0204081 
 -0.15655     0.133813     0.159091       -0.461605     0.2       
 -0.0984845   0.0253807    0.17647     …   0.182692    -0.0833333 
  0.453782   -0.0528713   -0.00466662      0.170732     0.0915152 
 -0.15607     0.123144     0.00803746     -0.280093     0.0688506 
  ⋮                                    ⋱                          
 -0.107697   -0.0439482   -0.0903226

In [12]:
expected_monthly_return_15 = get_expected_monthly_return(total_monthly_return_15)
cov_matrix_15 = get_cov_matrix(total_monthly_return_15, expected_monthly_return_15)

129×129 Array{Float64,2}:
  0.0226678    -0.00164294    0.000622467  …   0.00867433   0.00429746 
 -0.00164294    0.00829318    0.000996604     -0.0011917    0.0011988  
  0.000622467   0.000996604   0.0104447        0.000472707  0.001336   
  0.00217689    0.00185024    0.00215674       0.00341712   0.00199801 
 -0.000264272   0.00208967    0.00136046       0.000158642  0.00198801 
  0.00532297    0.00172085    0.00238859   …   0.00494921   0.00311222 
  0.0161282     0.000324373   0.00185512       0.0174276    0.00549434 
  0.00868097    0.00222622    0.00119386       0.010233     0.00399481 
  0.0043248    -0.00110706   -8.4115e-5        0.011878     0.00119186 
  0.0101926    -0.00178298    0.000131288      0.0120719    0.00444719 
  0.00112706    0.0014516     0.00156047   …   0.00104211   0.000799915
  0.00304015    0.00170215    0.00224391       0.00321934   0.00217468 
  0.00926067    0.00143387    0.000650334      0.00995883   0.00474411 
  ⋮                                   

In [13]:
# 2000-2015 risk free
baseline_profit = risk_free_15
# baseline_profit = sum(expected_monthly_return_15)/length_15
mT = transpose(expected_monthly_return_15)
cov = cov_matrix_15

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))

@variable(m, w[1:num_stock])
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

Optimal


129-element Array{Float64,1}:
  0.05205708211236412 
  0.16424080763461782 
 -0.08077104431565989 
  0.06264544627520525 
 -0.14837640835675703 
 -0.11214441698177009 
 -0.04081221914668509 
 -0.07114929983071001 
  0.13312638353359962 
 -0.032927831307456724
 -0.0302743056962417  
  0.041685584756914966
  0.29730513954506976 
  ⋮                   
 -0.18679720196760255 
 -0.14959534440078087 
  0.1765324143589622  
 -0.061112907654419756
  0.24422763933384095 
  0.24695093698929665 
 -0.15859868604806393 
 -0.24177474251002    
  0.08055968959985271 
  0.09279167006007527 
 -0.016501918876240782
  0.018055526984987514

In [14]:
# 2000-2015 index
baseline_profit = mean(index_monthly_return_15)
# baseline_profit = sum(expected_monthly_return_15)/length_15
mT = transpose(expected_monthly_return_15)
cov = cov_matrix_15

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))

@variable(m, w[1:num_stock])
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
  0.01075847684029408 
  0.062069842724571396
  0.005344786998251666
 -0.13835651332957086 
 -0.14337893920208494 
  0.052320973134375066
 -0.042481784113803676
 -0.08514915495732239 
  0.0397728096991244  
  0.0213247354262065  
  0.018224483260470173
 -0.07488425200073953 
 -0.06274895378738177 
  ⋮                   
 -0.131964675011162   
  0.016293509275082895
  0.06590061994110956 
  0.1472150317407254  
  0.04732109339503089 
  0.03165898617138159 
  0.15354083829267443 
  0.013729996018217136
  0.03907934762420442 
  0.21512268445812174 
 -0.025581005586628125
  0.04741994739648087 

In [15]:
# 2000-2015 equally weighted
baseline_profit = mean(expected_monthly_return_15)
# baseline_profit = sum(expected_monthly_return_15)/length_15
mT = transpose(expected_monthly_return_15)
cov = cov_matrix_15

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))

@variable(m, w[1:num_stock])
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
  0.08464572977214564 
  0.2448637137734302  
 -0.14872487631870446 
  0.2212556946681672  
 -0.15231990137304868 
 -0.24192373072407886 
 -0.03949476873643228 
 -0.060102041866337046
  0.20679150383078973 
 -0.07573842431113376 
 -0.06854460404709965 
  0.13367061216466933 
  0.5814231117810164  
  ⋮                   
 -0.23006544043490812 
 -0.28049791041999406 
  0.26383174431214773 
 -0.2255040721964453  
  0.39960620491083143 
  0.41683738915811247 
 -0.4049073667509396  
 -0.4433930258502831  
  0.11329174533264133 
 -0.003739491218092218
 -0.009337629527281052
 -0.005115879027862329

In [16]:
using CSV, LinearAlgebra
# remove those files(not long enough)
length_10 = 180-60-1
total_monthly_return_10 = zeros(length_10)

for i in 1:num_stock
    total_monthly_return_10 = hcat(total_monthly_return_10, get_monthly_return_stock(valid_data[61:180,i]))
end    

total_monthly_return_10 = total_monthly_return_10[:, 2:end]

119×129 Array{Float64,2}:
  0.16671     0.0277968   -0.00413227  …   0.0346009    0.0524272 
 -0.0711101  -0.0435726    0.019917       -0.0321192    0.0621157 
 -0.134629    0.0696457   -0.268104       -0.0783441   -0.0936113 
  0.102607    0.053688     0.103391        0.0308092    0.0922062 
 -0.0741951   0.0709308    0.077078       -0.0817429    0.0154026 
  0.158652    0.0381779    0.0729655   …   0.111765     0.00518436
  0.0994138   0.040117    -0.0187446      -0.00952381  -0.094938  
  0.143314    0.0352217    0.0955131      -0.00819088   0.0217392 
  0.07424    -0.0133248   -0.0117599      -0.140036     0.050816  
  0.177635    0.0534942   -0.0328273       0.103967    -0.0408885 
  0.0600118   0.0304916    0.0462452   …  -0.0465205   -0.0391473 
  0.0503547   0.0541062    0.277372        0.117017     0.0552474 
 -0.0929678   0.0538497    0.0069841      -0.03125     -0.0357792 
  ⋮                                    ⋱                          
 -0.107697   -0.0439482   -0.0903226

In [17]:
expected_monthly_return_10 = get_expected_monthly_return(total_monthly_return_10)
cov_matrix_10 = get_cov_matrix(total_monthly_return_10, expected_monthly_return_10)

129×129 Array{Float64,2}:
 0.00884296   0.000740552   0.00112632   …  0.00208645   0.00266909 
 0.000740552  0.00292671    0.000703173     0.00130032   0.000918648
 0.00112632   0.000703173   0.00688703      0.000985165  0.00104175 
 0.00125489   0.00111254    0.000990962     0.00116032   0.00127278 
 0.000671267  0.000762714   0.000514824     0.000882854  0.000993186
 0.00346078   0.00182497    0.00105365   …  0.00383127   0.0029     
 0.00544862   0.00264863    0.00145819      0.00603374   0.00304246 
 0.003792     0.00232649    0.000546522     0.00372281   0.00352729 
 0.00246195   0.000875993   0.000538722     0.00125441   0.000936933
 0.00365474   0.000679229  -1.7115e-6       0.00338646   0.00257509 
 0.00163581   0.00080084    0.000780148  …  0.00148172   0.00108278 
 0.00301957   0.00117867    0.00100302      0.00237914   0.00213695 
 0.00372811   0.00166286    0.00100846      0.00316325   0.00248489 
 ⋮                                       ⋱                          
 0.00581

In [18]:
# 2005-2015 risk-free
baseline_profit = risk_free_10
# baseline_profit = sum(expected_monthly_return_10)/length_10
mT = transpose(expected_monthly_return_10)
cov = cov_matrix_10

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))
@variable(m, w[1:num_stock] >= 0)
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
 0.3513000737882712   
 3.1526641524578017e-6
 7.632852004787723e-7 
 4.843162111828505e-7 
 3.5399142543062926e-7
 4.980297935475188e-7 
 1.8108471433763118e-7
 5.066284397305023e-7 
 1.015039073987516e-6 
 1.5359367250599971e-6
 8.931495200690383e-7 
 3.624131077506856e-7 
 7.025578340711965e-7 
 ⋮                    
 2.401402854891694e-7 
 3.0348928987405016e-7
 4.901099693347951e-7 
 3.654646969841553e-7 
 1.3446872735355094e-6
 5.451718545200605e-7 
 3.7098778880670495e-7
 3.756291943808678e-7 
 4.557312118498781e-7 
 4.326246868365292e-7 
 3.112136983673777e-7 
 5.040563074214958e-7 

In [19]:
# 2005-2015 index
baseline_profit = mean(index_monthly_return_10)
# baseline_profit = sum(expected_monthly_return_15)/length_15
mT = transpose(expected_monthly_return_10)
cov = cov_matrix_10

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))

@variable(m, w[1:num_stock] >= 0)
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
 6.0741538532358805e-6
 0.021471926390341838 
 0.0011730301017139682
 2.6226678359631782e-5
 1.0993376977953288e-5
 4.066507989206471e-6 
 1.8752673091247251e-6
 1.7006775680566362e-6
 0.05759166431638319  
 3.95821769789563e-6  
 0.035971296474877346 
 6.079213866356719e-6 
 2.8924707314699687e-6
 ⋮                    
 1.7263371069671088e-6
 3.85434625198967e-6  
 0.000163957730884722 
 1.7036778572277386e-5
 1.0121603116707708e-5
 3.199337666205788e-6 
 0.00064891654939836  
 7.076054916738684e-6 
 2.3046793974671988e-5
 0.14290115472058493  
 4.548156041273254e-6 
 6.0532409929550216e-6

In [20]:
# 2005-2015 equally weighted
baseline_profit = mean(expected_monthly_return_10)
# baseline_profit = sum(expected_monthly_return_10)/length_10
mT = transpose(expected_monthly_return_10)
cov = cov_matrix_10

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))
@variable(m, w[1:num_stock] >= 0)
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
 0.9774244644277528   
 3.1715364001346465e-8
 1.5382806298361245e-8
 1.330216867712195e-8 
 9.51477976018853e-9  
 1.9872907892507558e-8
 5.225903784924334e-9 
 2.5805510585739498e-8
 2.4068374287519098e-8
 7.040539575872053e-8 
 2.1508102037490435e-8
 1.4212788125417303e-8
 2.7478571889857854e-8
 ⋮                    
 1.3767559454634381e-8
 9.936953993792494e-9 
 1.464589098090727e-8 
 1.2229644567741976e-8
 3.022783120354963e-8 
 1.6907811948986615e-8
 9.154227350983515e-9 
 1.3301825131792953e-8
 1.773841957866201e-8 
 1.0231804373662613e-8
 9.790393539257079e-9 
 1.7999056464402436e-8

In [ ]:
#####3.2

In [115]:

using JuMP, Gurobi, Mosek
function linear_regression(r_stock, r_m)
    # m = Model(solver=MosekSolver(LOG=0))
    m = Model(solver=GurobiSolver(OutputFlag=0,BarHomogeneous=1))
    #m = Model(solver=GurobiSolver(OutputFlag=0,NumericFocus=3,BarHomogeneous=1))

    @variable(m, u[1:2])
    @objective(m, Min, sum( (r_stock - (r_m*u[2]+u[1])).^2 ) )
    status = solve(m)
    uopt = getvalue(u)
    err_term = getobjectivevalue(m)
    return uopt, err_term
end

linear_regression (generic function with 1 method)

In [184]:
var_index = var(index_monthly_return_15, corrected=false)
# a_vec = Float64[]
b_vec = Float64[]
err_vec = Float64[]
expected_monthly_return_removed = Float64[]
var_err_stock = Float64[]
mean_err_stock = Float64[]
for stock in 1:num_stock
    monthly_return_stock = total_monthly_return[1:length_15,stock]
    mean_15 = mean(monthly_return_stock)
    distance_15 = [(i-mean_15)^2 for i in monthly_return_stock]
    # remove 5% = 9 extreme values
    remove_h = sort(distance_15, rev=true)[1:9]
    remove_h_index_all = [findall(x -> x== i, distance_15) for i in remove_h]
    remove_h_index = collect(Iterators.flatten(remove_h_index_all))
    new_monthly_return_stock = Float64[]
    new_index_monthly_return = Float64[]
    for i in 1:length_15
        if !(i in remove_h_index)
            append!(new_monthly_return_stock, monthly_return_stock[i])
            append!(new_index_monthly_return, index_monthly_return_15[i])
        end
    end
    append!(expected_monthly_return_removed, mean(new_monthly_return_stock))
    (a, err_term) = linear_regression(new_monthly_return_stock, new_index_monthly_return)
    # append!(a_vec, a[1])
    append!(b_vec, a[2])
    append!(err_vec, err_term)
    # var_market = var(new_index_monthly_return, corrected=false)
    err = new_monthly_return_stock - (new_index_monthly_return.*a[2].+a[1])
    append!(var_err_stock, var(err))
    append!(mean_err_stock, mean(err))
end

Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic license - for non-commercial use only
Academic lice

In [177]:
# cov_stock = [[b_vec[i]*b_vec[j]*var_index for j in 1:num_stock] for i in 1:num_stock]
# err_correction = [[] for i in 1:num_stock]

cov_stock = transpose(zeros(num_stock))
# transpose([b_vec[i]*b_vec[j]*var_index for j in 1:num_stock])
for i in 1:num_stock
    cov_stock = vcat(cov_stock, transpose([b_vec[i]*b_vec[j]*var_index for j in 1:num_stock]))
end

cov_stock = cov_stock[2:end, :]

129×129 Array{Float64,2}:
 0.0023941    0.000711447  0.00117492   …  0.00279611   0.00153971 
 0.000711447  0.000211418  0.000349147     0.000830912  0.00045755 
 0.00117492   0.000349147  0.0005766       0.00137221   0.000755622
 0.00154838   0.000460127  0.000759878     0.00180838   0.000995804
 0.000716853  0.000213025  0.0003518       0.000837226  0.000461027
 0.00232131   0.000689817  0.0011392    …  0.00271111   0.0014929  
 0.0048785    0.00144973   0.00239416      0.00569769   0.00313749 
 0.00349447   0.00103844   0.00171494      0.00408126   0.00224739 
 0.0015987    0.00047508   0.000784572     0.00186715   0.00102816 
 0.00234988   0.000698307  0.00115322      0.00274447   0.00151127 
 0.000869768  0.000258466  0.000426844  …  0.00101582   0.00055937 
 0.00165751   0.000492555  0.000813432     0.00193583   0.00106598 
 0.00299212   0.00088916   0.00146841      0.00349456   0.00192431 
 ⋮                                      ⋱                          
 0.0026884    0.000798

In [181]:
# with a bias-correction term
cov_stock = cov_stock .+ (length_15-1)/(length_15-2).*Diagonal(mean_err_stock)

129×129 Array{Float64,2}:
 0.0023941    0.000711447  0.00117492   …  0.00279611   0.00153971 
 0.000711447  0.000211418  0.000349147     0.000830912  0.00045755 
 0.00117492   0.000349147  0.0005766       0.00137221   0.000755622
 0.00154838   0.000460127  0.000759878     0.00180838   0.000995804
 0.000716853  0.000213025  0.0003518       0.000837226  0.000461027
 0.00232131   0.000689817  0.0011392    …  0.00271111   0.0014929  
 0.0048785    0.00144973   0.00239416      0.00569769   0.00313749 
 0.00349447   0.00103844   0.00171494      0.00408126   0.00224739 
 0.0015987    0.00047508   0.000784572     0.00186715   0.00102816 
 0.00234988   0.000698307  0.00115322      0.00274447   0.00151127 
 0.000869768  0.000258466  0.000426844  …  0.00101582   0.00055937 
 0.00165751   0.000492555  0.000813432     0.00193583   0.00106598 
 0.00299212   0.00088916   0.00146841      0.00349456   0.00192431 
 ⋮                                      ⋱                          
 0.0026884    0.000798

In [185]:
# 2000-2015 risk free remove 5% extreme values
baseline_profit = risk_free_15
# baseline_profit = sum(expected_monthly_return_15)/length_15
mT = transpose(expected_monthly_return_removed)
cov = cov_stock

using JuMP, Gurobi, Ipopt
# m = Model(solver=GurobiSolver(OutputFlag=0))
m = Model(solver=IpoptSolver(print_level=0))

@variable(m, w[1:num_stock])
@objective(m, Min, dot(w,cov*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
  0.25408653653394314 
  0.06668407191411285 
 -0.03174351375437464 
 -0.04425665461346221 
 -0.029529786281366613
  0.013692155259288026
 -0.2684501576475007  
  0.09825361227377133 
 -0.03996569190378858 
  0.039176341620236886
  0.025558372411297027
 -0.020967625950404647
  0.10421569220575849 
  ⋮                   
  0.021313528017065802
  0.031983316938161435
  0.14850185732270044 
  0.028388754086167353
  0.05292535887752809 
  0.08634731643194012 
 -0.11091005341886215 
  0.03150324438890131 
 -0.012781601428102408
 -0.06457883134578521 
 -0.033731839996382296
  0.010947746834897097

In [212]:
#3.3
# 2000-2015 index
target_profit = mean(index_monthly_return_15)
mT = transpose(expected_monthly_return_15)
cov = cov_matrix_15
tune_factor = 100

using JuMP, Gurobi, Ipopt
m = Model(solver=IpoptSolver(print_level=0))

@variable(m, w[1:num_stock])
@variable(m, t[1:num_stock])
@constraint(m,  w .<= t)
@constraint(m, -w .<= t)
@constraint(m,  t .<= 1)
@constraint(m, mT*w >= target_profit )
@constraint(m, sum(w[i] for i in 1:num_stock) == 1)
@objective(m, Min, sum([target_profit - (transpose(total_monthly_return_15[t,:])*w)^2 for t in 1:length_15]) + tune_factor*sum(t) )

status = solve(m)
println(status) 
xsol = getvalue(w)

Optimal


129-element Array{Float64,1}:
 -1.6207662362678597e-10
 -3.7212465921299124e-11
 -5.14205436727226e-11  
 -3.4229183582207657e-11
  1.0559060516437935e-10
  1.565772258716753e-11 
 -1.0000000198284937    
 -4.411590590642938e-11 
  4.495611328056239e-11 
 -1.0446077134756881e-10
 -2.0161026018515736e-11
 -1.543923077838823e-10 
  9.571813405701516e-12 
  ⋮                     
 -1.909019325198696e-11 
  8.700114151267917e-11 
 -1.6806573808388643e-12
  6.304278422989994e-12 
 -4.636325315044644e-11 
  1.0000000199249472    
 -2.951503897747029e-11 
  1.793789090944814e-10 
  1.0000000197183423    
 -4.917651084638691e-11 
  1.941353809961095e-11 
 -1.0000000198644128    

In [214]:
for i in 1:num_stock
    if abs(xsol[i]) > 0.01
        println(i)
        println(xsol[i])
    end
end

7
-1.0000000198284937
16
1.0000000199113575
18
1.0000000199573624
19
1.0000000199362626
26
-1.0000000197852699
28
-1.0000000199010561
31
-1.0000000198978058
32
-1.0000000199346186
35
-1.0000000198949812
38
1.000000019999996
39
1.000000019875882
44
1.0000000198988401
45
-1.0000000199675614
46
1.0000000199811612
51
1.000000019004049
68
1.0000000199683905
73
1.000000019662806
76
1.0000000195623702
83
-1.0000000197658778
89
1.000000019965632
91
-1.0000000197161647
93
1.000000002886523
94
-1.0000000199370884
97
-1.000000019883709
99
-1.0000000199542693
105
-1.0000000199009005
111
1.0000000199619983
113
-1.000000019888663
123
1.0000000199249472
126
1.0000000197183423
129
-1.0000000198644128


In [207]:
data_files[70]

"HII.csv"