In [1]:
using CSV, LinearAlgebra
slb = CSV.read("top30/SLB.csv") 

292×7 DataFrames.DataFrame. Omitted printing of 1 columns
│ Row │ Date      │ Open     │ High     │ Low      │ Close    │ Adj Close │
│     │ String⍰   │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰  │
├─────┼───────────┼──────────┼──────────┼──────────┼──────────┼───────────┤
│ 1   │ 1/1/1995  │ 12.6875  │ 13.6875  │ 12.5313  │ 13.1875  │ 5.30775   │
│ 2   │ 2/1/1995  │ 13.25    │ 14.4375  │ 13.125   │ 14.2188  │ 5.72281   │
│ 3   │ 3/1/1995  │ 14.3125  │ 15.0313  │ 14.125   │ 14.9063  │ 6.13059   │
│ 4   │ 4/1/1995  │ 14.9063  │ 16.0     │ 14.5313  │ 15.7188  │ 6.60074   │
│ 5   │ 5/1/1995  │ 15.875   │ 16.5938  │ 15.6563  │ 16.25    │ 6.82382   │
│ 6   │ 6/1/1995  │ 16.25    │ 16.6563  │ 15.375   │ 15.5313  │ 6.80504   │
│ 7   │ 7/1/1995  │ 15.5313  │ 16.9688  │ 15.4375  │ 16.75    │ 7.33903   │
│ 8   │ 8/1/1995  │ 16.6875  │ 16.7188  │ 15.3125  │ 16.125   │ 7.06519   │
│ 9   │ 9/1/1995  │ 16.375   │ 17.4063  │ 15.8125  │ 16.3438  │ 7.51654   │
│ 10  │ 10/1/1995 │ 16.3438  │ 17.0625  │ 14.7188  │ 15.5625  │ 7.15724   │
⋮
│ 282 │ 6/1/2018  │ 68.64    │ 70.47    │ 64.51    │ 67.03    │ 64.5577   │
│ 283 │ 7/1/2018  │ 66.45    │ 69.61    │ 64.73    │ 67.52    │ 65.5038   │
│ 284 │ 8/1/2018  │ 67.0     │ 67.31    │ 61.82    │ 63.16    │ 61.274    │
│ 285 │ 9/1/2018  │ 63.06    │ 63.14    │ 59.25    │ 60.92    │ 59.1009   │
│ 286 │ 10/1/2018 │ 61.2     │ 63.65    │ 50.8     │ 51.31    │ 50.175    │
│ 287 │ 11/1/2018 │ 51.6     │ 52.94    │ 44.68    │ 45.1     │ 44.1024   │
│ 288 │ 12/1/2018 │ 46.28    │ 46.61    │ 34.99    │ 36.08    │ 35.2819   │
│ 289 │ 1/1/2019  │ 35.49    │ 45.05    │ 35.34    │ 44.21    │ 43.704    │
│ 290 │ 2/1/2019  │ 44.4     │ 46.35    │ 42.23    │ 44.06    │ 43.5558   │
│ 291 │ 3/1/2019  │ 44.22    │ 45.66    │ 40.88    │ 43.57    │ 43.57     │
│ 292 │ 4/1/2019  │ 43.98    │ 48.88    │ 42.46    │ 43.3     │ 43.3      │

In [2]:
(size(slb))[1]

292

In [3]:
slb[2,2]

13.25

In [4]:
slb_return

UndefVarError: UndefVarError: slb_return not defined

In [5]:
data_files = readdir("top30")

164-element Array{String,1}:
 "AAPL.csv"
 "ABBV.csv"
 "ABC.csv" 
 "ADM.csv" 
 "ADP.csv" 
 "ADS.csv" 
 "AEP.csv" 
 "AIZ.csv" 
 "ALB.csv" 
 "ALGN.csv"
 "AMD.csv" 
 "AMG.csv" 
 "AMT.csv" 
 ⋮         
 "UTX.csv" 
 "V.csv"   
 "VFC.csv" 
 "VTR.csv" 
 "VZ.csv"  
 "WAT.csv" 
 "WMB.csv" 
 "WMT.csv" 
 "WRK.csv" 
 "WYNN.csv"
 "XLNX.csv"
 "YUM.csv" 

In [6]:
comp_name = CSV.read("data/constituents_csv.csv")
for i in 1:((size(comp_name))[1]-1)
    #println("https://query1.finance.yahoo.com/v7/finance/download/",comp_name[i,1],"?period1=946706400&period2=1514786400&interval=1mo&events=history&crumb=UB6zx5WdF5I")
end    

In [7]:
url_csv = []
for i in 1:((size(comp_name))[1]-1)
    push!(url_csv, "https://query1.finance.yahoo.com/v7/finance/download/",comp_name[i,1],"?period1=946706400&period2=1514786400&interval=1mo&events=history&crumb=UB6zx5WdF5I")
end    

In [8]:
# open("url.docx", "w") do f
#     for url in url_csv
#         write(f, url_csv, "\n")
#     end
# end    

In [9]:
# HELPER FUNCTION TO CALCULATE RATIO OF RETURN
# ratio of return in a monthly base
function get_monthly_return(csv_data)
    montly_return = Float64[]
    for i in 1:((size(csv_data))[1]-1)
        append!(montly_return, (csv_data[i+1,5]-csv_data[i,5])/csv_data[i,5])
    end  
    return montly_return
end;    

In [10]:
# repeatedly run to remove those files(not long enough)
data_files = readdir("top30")
for i in data_files
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    csv_length = (size(csv_data))[1]
    # check all csv has the same length (no new/removed S&P 500)
    if csv_length != 216
        print(file_path, ": ")
        println(csv_length)
    end
    get_monthly_return(csv_data)
end    

top30/ABBV.csv: 60
top30/ADS.csv: 199
top30/AIZ.csv: 167
top30/ALGN.csv: 204
top30/AVGO.csv: 101
top30/AYI.csv: 193
top30/CBOE.csv: 91
top30/CME.csv: 181
top30/DG.csv: 98
top30/DISCA.csv: 150
top30/DXC.csv: 217
top30/EQIX.csv: 209
top30/FTV.csv: 18
top30/GOOGL.csv: 161
top30/HCA.csv: 82
top30/HII.csv: 82
top30/HLT.csv: 49
top30/KHC.csv: 30
top30/KMI.csv: 83
top30/LYB.csv: 93
top30/MDLZ.csv: 199
top30/NAVI.csv: 45
top30/NLSN.csv: 84
top30/NRG.csv: 169
top30/NWSA.csv: 55
top30/PM.csv: 118
top30/PPG.csv: 2
top30/RTN.csv: 292
top30/SLB.csv: 292
top30/STX.csv: 181
top30/SYF.csv: 42
top30/TDG.csv: 142
top30/TEL.csv: 127
top30/TXN.csv: 292
top30/UA.csv: 30
top30/V.csv: 118
top30/WRK.csv: 31
top30/WYNN.csv: 183


In [11]:
data_files = readdir("top30")
for i in data_files
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    get_monthly_return(csv_data)
end    

In [16]:
# filter!(x->x≠"AVGO.csv", data_files)

163-element Array{String,1}:
 "AAPL.csv"
 "ABBV.csv"
 "ABC.csv" 
 "ADM.csv" 
 "ADP.csv" 
 "ADS.csv" 
 "AEP.csv" 
 "AIZ.csv" 
 "ALB.csv" 
 "ALGN.csv"
 "AMD.csv" 
 "AMG.csv" 
 "AMT.csv" 
 ⋮         
 "UTX.csv" 
 "V.csv"   
 "VFC.csv" 
 "VTR.csv" 
 "VZ.csv"  
 "WAT.csv" 
 "WMB.csv" 
 "WMT.csv" 
 "WRK.csv" 
 "WYNN.csv"
 "XLNX.csv"
 "YUM.csv" 

In [35]:
data_files = readdir("top30")
println("Previous contains ", length(data_files), " data files")
remove_file_id = Int64[]
for i in 1:length(data_files)
    file_name = data_files[i]
    file_path = string("top30/", file_name)
    csv_data = CSV.read(file_path) 
    csv_length = (size(csv_data))[1]
    # check all csv has the same length (no new/removed S&P 500)
    if csv_length != 216
        print(file_path, ": ")
        println(csv_length)
        # deleteat!(data_files, i)
        push!(remove_file_id, i)
    else
        # println(get_monthly_return(csv_data))
    end
end  
for i in remove_file_id[end:-1:1]
    deleteat!(data_files, i)
end
println("Now contains ", length(data_files), " valid data files")

Previous contains 164 data files
top30/ABBV.csv: 60
top30/ADS.csv: 199
top30/AIZ.csv: 167
top30/ALGN.csv: 204
top30/AVGO.csv: 101
top30/AYI.csv: 193
top30/CBOE.csv: 91
top30/CME.csv: 181
top30/DG.csv: 98
top30/DISCA.csv: 150
top30/EQIX.csv: 209
top30/FTV.csv: 18
top30/GOOGL.csv: 161
top30/HCA.csv: 82
top30/HII.csv: 82
top30/HLT.csv: 49
top30/KHC.csv: 30
top30/KMI.csv: 83
top30/LYB.csv: 93
top30/MDLZ.csv: 199
top30/NAVI.csv: 45
top30/NLSN.csv: 84
top30/NRG.csv: 169
top30/NWSA.csv: 55
top30/PM.csv: 118
top30/PPG.csv: 2
top30/RTN.csv: 276
top30/STX.csv: 181
top30/SYF.csv: 42
top30/TDG.csv: 142
top30/TEL.csv: 127
top30/UA.csv: 30
top30/V.csv: 118
top30/WRK.csv: 31
top30/WYNN.csv: 183
Now contains 129 valid data files


In [44]:
# data_files = readdir("top30")
total_monthly_return = zeros(215)
for i in data_files    
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    total_monthly_return = hcat(total_monthly_return, get_monthly_return(csv_data))
end    

In [55]:
permutedims(data_files)

1×129 Array{String,2}:
 "AAPL.csv"  "ABC.csv"  "ADM.csv"  …  "WMT.csv"  "XLNX.csv"  "YUM.csv"

In [56]:
reshape(data_files, 1, :)

1×129 Array{String,2}:
 "AAPL.csv"  "ABC.csv"  "ADM.csv"  …  "WMT.csv"  "XLNX.csv"  "YUM.csv"

In [57]:
# m
total_monthly_return = total_monthly_return[:, 2:end]

215×129 Array{Float64,2}:
  0.104819    -0.196552    -0.143617    …   0.743169   -0.0698691 
  0.184842     0.0300429    0.0248447       0.0384013   0.166667  
 -0.0865162    0.333333    -0.0363637      -0.115472    0.0905433 
 -0.322922     0.2125       0.201258        0.0392491  -0.134686  
  0.247024     0.278994    -0.17801         0.0845649  -0.0362474 
 -0.0298329    0.126449    -0.0445859   …  -0.0908403  -0.141593  
  0.199262     0.00536673  -0.0112529       0.184013    0.201674  
 -0.577436     0.338078    -0.023006       -0.0365682   0.0509393 
 -0.240292    -0.0757979    0.275362       -0.154015   -0.0204081 
 -0.15655      0.133813     0.159091       -0.461605    0.2       
 -0.0984845    0.0253807    0.17647     …   0.182692   -0.0833333 
  0.453782    -0.0528713   -0.00466662      0.170732    0.0915152 
 -0.15607      0.123144     0.00803746     -0.280093    0.0688506 
  ⋮                                     ⋱                         
  0.0477465    0.116255    -0.030449

In [58]:
cov(total_monthly_return[:,1], false)

UndefVarError: UndefVarError: cov not defined