In [1]:
using CSV, LinearAlgebra
slb = CSV.read("top30/SLB.csv") 

216×7 DataFrames.DataFrame. Omitted printing of 1 columns
│ Row │ Date      │ Open     │ High     │ Low      │ Close    │ Adj Close │
│     │ String⍰   │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰  │
├─────┼───────────┼──────────┼──────────┼──────────┼──────────┼───────────┤
│ 1   │ 1/1/2000  │ 27.8125  │ 33.8125  │ 26.75    │ 30.5313  │ 20.2925   │
│ 2   │ 2/1/2000  │ 30.9688  │ 36.9375  │ 28.4688  │ 36.9297  │ 24.5452   │
│ 3   │ 3/1/2000  │ 37.9063  │ 42.1875  │ 34.7188  │ 38.25    │ 25.567    │
│ 4   │ 4/1/2000  │ 39.0     │ 41.375   │ 33.4063  │ 38.2813  │ 25.5879   │
│ 5   │ 5/1/2000  │ 38.1563  │ 42.125   │ 34.625   │ 36.7813  │ 24.5852   │
│ 6   │ 6/1/2000  │ 36.7813  │ 39.75    │ 34.5313  │ 37.3125  │ 24.9403   │
│ 7   │ 7/1/2000  │ 37.1875  │ 38.5938  │ 34.3125  │ 36.9609  │ 24.839    │
│ 8   │ 8/1/2000  │ 37.1875  │ 44.4375  │ 37.0625  │ 42.6641  │ 28.6716   │
│ 9   │ 9/1/2000  │ 42.5625  │ 43.8438  │ 38.0938  │ 41.1563  │ 27.6583   │
│ 10  │ 10/1/2000 │ 41.5625  │ 43.1875  │ 36.2813  │ 38.0625  │ 25.6922   │
⋮
│ 206 │ 2/1/2017  │ 84.06    │ 84.44    │ 79.48    │ 80.36    │ 74.6616   │
│ 207 │ 3/1/2017  │ 80.91    │ 82.69    │ 76.14    │ 78.1     │ 73.0061   │
│ 208 │ 4/1/2017  │ 78.3     │ 80.89    │ 72.1     │ 72.59    │ 67.8555   │
│ 209 │ 5/1/2017  │ 72.7     │ 73.2     │ 68.23    │ 69.59    │ 65.0511   │
│ 210 │ 6/1/2017  │ 69.67    │ 70.69    │ 65.1     │ 65.84    │ 61.9879   │
│ 211 │ 7/1/2017  │ 66.12    │ 69.04    │ 64.15    │ 68.6     │ 64.5865   │
│ 212 │ 8/1/2017  │ 68.5     │ 69.37    │ 62.56    │ 63.51    │ 59.7943   │
│ 213 │ 9/1/2017  │ 63.2     │ 70.01    │ 62.97    │ 69.76    │ 65.6786   │
│ 214 │ 10/1/2017 │ 68.73    │ 69.57    │ 61.4     │ 64.0     │ 60.7337   │
│ 215 │ 11/1/2017 │ 64.62    │ 67.68    │ 61.02    │ 62.85    │ 59.6424   │
│ 216 │ 12/1/2017 │ 63.23    │ 68.4     │ 61.78    │ 67.39    │ 63.9507   │

In [2]:
(size(slb))[1]

216

In [3]:
slb[2,2]

30.96875

In [4]:
slb_return

UndefVarError: UndefVarError: slb_return not defined

In [5]:
data_files = readdir("top30")

164-element Array{String,1}:
 "AAPL.csv"
 "ABBV.csv"
 "ABC.csv" 
 "ADM.csv" 
 "ADP.csv" 
 "ADS.csv" 
 "AEP.csv" 
 "AIZ.csv" 
 "ALB.csv" 
 "ALGN.csv"
 "AMD.csv" 
 "AMG.csv" 
 "AMT.csv" 
 ⋮         
 "UTX.csv" 
 "V.csv"   
 "VFC.csv" 
 "VTR.csv" 
 "VZ.csv"  
 "WAT.csv" 
 "WMB.csv" 
 "WMT.csv" 
 "WRK.csv" 
 "WYNN.csv"
 "XLNX.csv"
 "YUM.csv" 

In [6]:
comp_name = CSV.read("data/constituents_csv.csv")
for i in 1:((size(comp_name))[1]-1)
    #println("https://query1.finance.yahoo.com/v7/finance/download/",comp_name[i,1],"?period1=946706400&period2=1514786400&interval=1mo&events=history&crumb=UB6zx5WdF5I")
end    

In [7]:
url_csv = []
for i in 1:((size(comp_name))[1]-1)
    push!(url_csv, "https://query1.finance.yahoo.com/v7/finance/download/",comp_name[i,1],"?period1=946706400&period2=1514786400&interval=1mo&events=history&crumb=UB6zx5WdF5I")
end    

In [8]:
# open("url.docx", "w") do f
#     for url in url_csv
#         write(f, url_csv, "\n")
#     end
# end    

In [9]:
# HELPER FUNCTION TO CALCULATE RATIO OF RETURN
# ratio of return in a monthly base
function get_monthly_return(csv_data)
    montly_return = Float64[]
    for i in 1:((size(csv_data))[1]-1)
        append!(montly_return, (csv_data[i+1,5]-csv_data[i,5])/csv_data[i,5])
    end  
    return montly_return
end;    

In [10]:
# repeatedly run to remove those files(not long enough)
data_files = readdir("top30")
for i in data_files
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    csv_length = (size(csv_data))[1]
    # check all csv has the same length (no new/removed S&P 500)
    if csv_length != 216
        print(file_path, ": ")
        println(csv_length)
    end
    get_monthly_return(csv_data)
end    

top30/ABBV.csv: 60
top30/ADS.csv: 199
top30/AIZ.csv: 167
top30/ALGN.csv: 204
top30/AVGO.csv: 101
top30/AYI.csv: 193
top30/CBOE.csv: 91
top30/CME.csv: 181
top30/DG.csv: 98
top30/DISCA.csv: 150
top30/EQIX.csv: 209
top30/FTV.csv: 18
top30/GOOGL.csv: 161
top30/HCA.csv: 82
top30/HII.csv: 82
top30/HLT.csv: 49
top30/KHC.csv: 30
top30/KMI.csv: 83
top30/LYB.csv: 93
top30/MDLZ.csv: 199
top30/NAVI.csv: 45
top30/NLSN.csv: 84
top30/NRG.csv: 169
top30/NWSA.csv: 55
top30/PM.csv: 118
top30/PPG.csv: 2
top30/RTN.csv: 276
top30/STX.csv: 181
top30/SYF.csv: 42
top30/TDG.csv: 142
top30/TEL.csv: 127
top30/UA.csv: 30
top30/V.csv: 118
top30/WRK.csv: 31
top30/WYNN.csv: 183


In [11]:
data_files = readdir("top30")
for i in data_files
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    get_monthly_return(csv_data)
end    

In [12]:
# filter!(x->x≠"AVGO.csv", data_files)

In [13]:
data_files = readdir("top30")
println("Previous contains ", length(data_files), " data files")
remove_file_id = Int64[]
for i in 1:length(data_files)
    file_name = data_files[i]
    file_path = string("top30/", file_name)
    csv_data = CSV.read(file_path) 
    csv_length = (size(csv_data))[1]
    # check all csv has the same length (no new/removed S&P 500)
    if csv_length != 216
        print(file_path, ": ")
        println(csv_length)
        # deleteat!(data_files, i)
        push!(remove_file_id, i)
    else
        # println(get_monthly_return(csv_data))
    end
end  
for i in remove_file_id[end:-1:1]
    deleteat!(data_files, i)
end
println("Now contains ", length(data_files), " valid data files")

Previous contains 164 data files
top30/ABBV.csv: 60
top30/ADS.csv: 199
top30/AIZ.csv: 167
top30/ALGN.csv: 204
top30/AVGO.csv: 101
top30/AYI.csv: 193
top30/CBOE.csv: 91
top30/CME.csv: 181
top30/DG.csv: 98
top30/DISCA.csv: 150
top30/EQIX.csv: 209
top30/FTV.csv: 18
top30/GOOGL.csv: 161
top30/HCA.csv: 82
top30/HII.csv: 82
top30/HLT.csv: 49
top30/KHC.csv: 30
top30/KMI.csv: 83
top30/LYB.csv: 93
top30/MDLZ.csv: 199
top30/NAVI.csv: 45
top30/NLSN.csv: 84
top30/NRG.csv: 169
top30/NWSA.csv: 55
top30/PM.csv: 118
top30/PPG.csv: 2
top30/RTN.csv: 276
top30/STX.csv: 181
top30/SYF.csv: 42
top30/TDG.csv: 142
top30/TEL.csv: 127
top30/UA.csv: 30
top30/V.csv: 118
top30/WRK.csv: 31
top30/WYNN.csv: 183
Now contains 129 valid data files


In [14]:
# data_files = readdir("top30")
total_monthly_return = zeros(215)
for i in data_files    
    file_path = string("top30/", i)
    csv_data = CSV.read(file_path) 
    total_monthly_return = hcat(total_monthly_return, get_monthly_return(csv_data))
end    

In [15]:
permutedims(data_files)

1×129 Array{String,2}:
 "AAPL.csv"  "ABC.csv"  "ADM.csv"  …  "WMT.csv"  "XLNX.csv"  "YUM.csv"

In [16]:
reshape(data_files, 1, :)

1×129 Array{String,2}:
 "AAPL.csv"  "ABC.csv"  "ADM.csv"  …  "WMT.csv"  "XLNX.csv"  "YUM.csv"

In [ ]:
function get_expected_monthly_return(y)
    using JuMP, Gurobi
    m = Model(solver=GurobiSolver(OutputFlag=0))
    @variable(m, x)
    @objective(m, Min, sum( (y-x).^2 ) )
    
    solve(m)
    println("The mean of y is: ", getvalue(x))
    return x
end

In [17]:
# m
total_monthly_return = total_monthly_return[:, 2:end]

215×129 Array{Float64,2}:
  0.104819    -0.196552    -0.143617    …   0.743169   -0.0698691 
  0.184842     0.0300429    0.0248447       0.0384013   0.166667  
 -0.0865162    0.333333    -0.0363637      -0.115472    0.0905433 
 -0.322922     0.2125       0.201258        0.0392491  -0.134686  
  0.247024     0.278994    -0.17801         0.0845649  -0.0362474 
 -0.0298329    0.126449    -0.0445859   …  -0.0908403  -0.141593  
  0.199262     0.00536673  -0.0112529       0.184013    0.201674  
 -0.577436     0.338078    -0.023006       -0.0365682   0.0509393 
 -0.240292    -0.0757979    0.275362       -0.154015   -0.0204081 
 -0.15655      0.133813     0.159091       -0.461605    0.2       
 -0.0984845    0.0253807    0.17647     …   0.182692   -0.0833333 
  0.453782    -0.0528713   -0.00466662      0.170732    0.0915152 
 -0.15607      0.123144     0.00803746     -0.280093    0.0688506 
  ⋮                                     ⋱                         
  0.0477465    0.116255    -0.030449

In [19]:
total_monthly_return=total_monthly_return[:,2:end]

215×128 Array{Float64,2}:
 -0.196552    -0.143617    -0.0816864    …   0.743169   -0.0698691 
  0.0300429    0.0248447    0.107604         0.0384013   0.166667  
  0.333333    -0.0363637    0.115285        -0.115472    0.0905433 
  0.2125       0.201258     0.0220674        0.0392491  -0.134686  
  0.278994    -0.17801     -0.0261363        0.0845649  -0.0362474 
  0.126449    -0.0445859   -0.0746791    …  -0.0908403  -0.141593  
  0.00536673  -0.0112529    0.203341         0.184013    0.201674  
  0.338078    -0.023006     0.1213          -0.0365682   0.0509393 
 -0.0757979    0.275362    -0.0233645       -0.154015   -0.0204081 
  0.133813     0.159091     0.0105264       -0.461605    0.2       
  0.0253807    0.17647     -0.0407198    …   0.182692   -0.0833333 
 -0.0528713   -0.00466662  -0.0545311        0.170732    0.0915152 
  0.123144     0.00803746  -0.0143668       -0.280093    0.0688506 
  ⋮                                      ⋱                         
  0.116255    -0.03044

In [27]:
using Statistics
# mean([2,5,7])
expected_monthly_return = Float64[]
for i in 1:size(total_monthly_return)[2]
    push!(expected_monthly_return, mean(total_monthly_return[:,i]))
end
expected_monthly_return

128-element Array{Float64,1}:
 0.016912595764853138 
 0.009564503171370812 
 0.007014600703790782 
 0.005397906212492487 
 0.016519475094170087 
 0.015524168594298294 
 0.016263200737921635 
 0.016155426487548447 
 0.023064400886971745 
 0.01092046897112602  
 0.01049504978008741  
 0.019188604844708784 
 0.005197276843331301 
 ⋮                    
 0.010202314552856976 
 0.009012570445919637 
 0.01900224488440054  
 0.009288300060753934 
 0.013756442432663793 
 0.016681222100094976 
 0.0019328706496993188
 0.012594881969745533 
 0.009612927352649934 
 0.004164458380570289 
 0.008563595437728933 
 0.015380230394524868 

In [32]:
transpose(total_monthly_return)

128×215 Transpose{Float64,Array{Float64,2}}:
 -0.196552    0.0300429    0.333333    …   0.102274     0.0825277 
 -0.143617    0.0248447   -0.0363637      -0.0242231    0.00501507
 -0.0816864   0.107604     0.115285       -0.0154826    0.0238512 
 -0.160448    0.06         0.228512        0.0432737   -0.0522993 
 -0.16609     0.377593     0.00903614     -0.0466321   -0.0478708 
  0.0972222   0.493671     0.483051    …  -0.00909918  -0.0560147 
  0.135379    0.208267    -0.155263        0.0652547    0.0331203 
  0.372822    0.00253807  -0.056962        0.00180967  -0.00875422
  0.0667957  -0.0272232   -0.176306        0.0646623   -0.00618656
 -0.18599     0.531157    -0.160853       -0.0223802   -0.0443589 
 -0.130802    0.104369     0.0923077   …   0.0226432    0.00637886
  0.177716    0.279124     0.246944        0.0412643   -0.030798  
 -0.104244    0.0061792    0.0747185       0.07488      0.00648438
  ⋮                                    ⋱                          
  0.0219895  -0.0

In [45]:
cov_matrix = transpose(total_monthly_return)*total_monthly_return./126-expected_monthly_return*transpose(expected_monthly_return)

128×128 Array{Float64,2}:
  0.0101211     0.00106254   0.00212201   …  -0.00129881   0.0016289 
  0.00106254    0.0117994    0.00244376       0.000753899  0.00135661
  0.00212201    0.00244376   0.00594098       0.00375372   0.00211177
  0.00197624    0.0013698    0.00186659       9.98264e-5   0.00216555
  0.00182979    0.0033003    0.0030029        0.00595434   0.00359229
  0.000888504   0.00314121   0.00649325   …   0.0185803    0.00602537
  0.00289469    0.0017889    0.00383528       0.0106053    0.00451914
 -0.00126558    0.00028777   0.00148417       0.0122978    0.00131009
 -0.00155969    0.000248789  0.00320006       0.0125004    0.00478311
  0.00167016    0.00181556   0.00161315       0.00134128   0.0011456 
  0.00201235    0.00259238   0.00247013   …   0.00365547   0.00232913
  0.00160188    0.00081701   0.00395171       0.0104517    0.00510865
  0.00158186    0.00159676   0.00265323       0.00335006   0.00357926
  ⋮                                       ⋱                     

In [35]:
# Σ
# cov_matrix = cov(transpose(total_monthly_return), expected_monthly_return)

215×1 Array{Float64,2}:
 -0.0538346266825579    
 -0.03790684177374644   
  0.008468111399452388  
  0.05906076909912983   
 -0.08544933180086396   
 -0.06509143338038721   
  0.06809842481372719   
 -0.015086995570200807  
 -0.06718470840194934   
  0.04965501508240355   
 -0.0714159389820257    
  0.016867317402016132  
 -0.010521381807744675  
  ⋮                     
  0.07218785306864074   
 -0.03160645182548581   
  0.061093544603485005  
 -0.023063266003166574  
  0.00804778151061554   
 -0.008423999732853847  
  0.00033057219458861687
  0.03440720607814084   
 -0.008796817263422019  
  0.017138551538431742  
  0.008972132938802085  
 -0.01031339357409998   

In [67]:
baseline_profit = 0.005
mT = transpose(expected_monthly_return)

using JuMP, Gurobi
m = Model(solver=GurobiSolver(OutputFlag=0))
@variable(m, w[1:128] >= 0)
@objective(m, Min, dot(w,cov_matrix*w) )
@constraint(m, mT*w >= baseline_profit )
@constraint(m, sum(w[i] for i in 1:128) == 1)

status = solve(m)
println(status) 
xsol = getvalue(w)

Academic license - for non-commercial use only
Optimal


128-element Array{Float64,1}:
 2.071096830664838e-8 
 0.012047703387721648 
 1.108264161276831e-8 
 6.02719572067859e-9  
 3.823450787764259e-9 
 1.4719912970799151e-9
 1.4922359575233983e-9
 0.01154282903944727  
 5.677598247094121e-9 
 0.005083127607038396 
 1.4337007521660563e-8
 2.9578732314115646e-9
 1.297621947840293e-8 
 ⋮                    
 3.1260156510331153e-9
 2.8396599137586596e-8
 2.280518749403952e-8 
 1.4444682879753576e-8
 1.3690416656420821e-8
 5.228467899479759e-9 
 1.7209477854174702e-7
 8.72772262105596e-9  
 1.2063880783670131e-8
 0.12307435879067989  
 8.290668590658833e-9 
 1.2842641322057818e-8

In [37]:
μ = expected_monthly_return
Σ = cov_matrix
ix = sortperm(μ);   # sort the assets by expected return

# using PyPlot
# fig = figure(figsize=(12,6))

# subplot(211)
# xlim(0,225)
# plot(sqrt.(diag(Σ))[ix],"g")
# ylabel("Standard deviation (%)")
# title("Standard deviation and expected return of all 225 assets")
# tight_layout()

# subplot(212)
# xlim(0,225)
# plot(μ[ix])
# plot([0,225],[0,0],"r--")
# ylabel("Expected return (%)")
# tight_layout()

In [40]:
using JuMP, Mosek
m = Model(solver = MosekSolver(LOG=0))
@variable(m, x[1:128] >= 0)
@constraint(m, sum(x) == 1)

# figure(figsize=(12,8))

# subplot(211)
λ = 1

@objective(m, Min, -dot(μ,x) + λ*dot(x,Σ*x) )
solve(m)
xsol = getvalue(x)
# ix1 = find(xsol .> 1e-4)
# ret = dot(μ,xsol)
# std = sqrt(dot(xsol,Σ*xsol))
# xlim(0,225)
# bar(1:225,xsol[ix])
# title(string("Optimal asset selection for \$\\lambda=1\$"," ( \$\\mu=\$", round(ret,3), "%, \$\\sigma=\$", round(std,2), "% )"));
# tight_layout()
# subplot(212)
# λ = 3e-2

# @objective(m, Min, -dot(μ,x) + λ*dot(x,Σ*x) )
# solve(m)
# xsol = getvalue(x)
# ix2 = find(xsol .> 1e-4)
# ret = dot(μ,xsol)
# std = sqrt(dot(xsol,Σ*xsol))
# xlim(0,225)
# bar(1:225,xsol[ix])
# title(string("Optimal asset selection for \$\\lambda=3\\times10^\{-2\}\$"," ( \$\\mu=\$", round(ret,3), "%, \$\\sigma=\$", round(std,2), "% )"));
# tight_layout()

# #savefig("folio4_optassets.pdf")

ErrorException: Incompatible sizes